### ISSUE TITLE
Suggestions for generating bcrypted passwords with bosh deploy/credhub?

### ISSUE THREAD

**Issue by drnic** [concourse/concourse-bosh-release#2]
https://github.com/concourse/concourse-bosh-release/blob/828cb5230f1e8f1519ef50fa18dee12eaaaf61a8/jobs/atc/spec#L164-L171

The method for specifying various local users is a list of strings that includes a bcrypted password. Ok. How do I generate a password and get its bcrypted version during `bosh deploy` from credhub?

E.g. an ops file like

```
- type: replace
  path: /instance_groups/name=web/jobs/name=atc/properties/add_local_users?/-
  value: "myteam-admin:((myteam-password.bcrypt))"

- type: replace
  path: /variables/-
  value:
    name: myteam-password
    type: password
```

Or is there a diff path for this?
