### ISSUE TITLE
bbr-atcdb job on postgres node error filling in template config.json.erb

### ISSUE THREAD

**Issue by gbark13** [concourse/concourse-bosh-release#32]
# Bug Report

getting this error deploying concourse
```
Task 11959 | 15:09:17 | Preparing deployment: Preparing deployment (00:00:02)
Task 11959 | 15:09:19 | Preparing deployment: Rendering templates (00:00:01)
                     L Error: Unable to render instance groups for deployment. Errors are:
  - Unable to render jobs for instance group 'db'. Errors are:
    - Unable to render templates for job 'bbr-atcdb'. Errors are:
      - Error filling in template 'config.json.erb' (line 61: Can't find property '["postgresql.ca_cert"]')
```

manifest for db is:
```
releases:
- name: concourse
  version: 5.2.0
  url: https://bosh.io/d/github.com/concourse/concourse-bosh-release?v=5.2.0
  sha1: e7c813d35e70e1a3a5334b977136ba736fae05e1
- name: bpm
  version: 1.0.4
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/bpm-release?v=1.0.4
  sha1: 41df19697d6a69d2552bc2c132928157fa91abe0
- name: postgres
  version: 37
  url: https://bosh.io/d/github.com/cloudfoundry/postgres-release?v=37
  sha1: 0bffec6b98df81219a18ec8da0e19721be799eed
- name: backup-and-restore-sdk
  version: 1.15.1
  url: https://bosh.io/d/github.com/cloudfoundry-incubator/backup-and-restore-sdk-release?v=1.15.1
  sha1: 364838c384f2edec80866b4abf2397c4c5d15c62
- name: haproxy
  version: 8.9.0
  url: https://github.com/cloudfoundry-incubator/haproxy-boshrelease/releases/download/v8.9.0/haproxy-8.9.0.tgz
  sha1: 0a135d9f5ce4e32dc9f1afd9a0e93baeff71c62d

stemcells:
- alias: xenial
  os: ubuntu-xenial
  version: 315.13

instance_groups:
- name: db
  instances: 1
  persistent_disk_type: ((db_persistent_disk_type))
  vm_type: ((db_vm_type))
  stemcell: xenial
  azs: [z1]
  networks:
  - name: tools-vsphere 
    static_ips: ((db_ip))
  jobs:
  - release: postgres
    name: postgres
    properties:
      databases:
        port: 5432
        databases:
        - name: atc
        roles:
        - name: atc
          password: ((atc-db-password))
  - release: backup-and-restore-sdk
    name: database-backup-restorer
  - release: concourse
    name: bbr-atcdb
```

I’ve tried several different combinations of properties on bbr-atcdb and not able to find a combination that doesn’t cause this error in the template.

Line 61 of config.json.erb is this
```
58:    if_link("concourse_db") do |cdb|
59:      postgres_tls_enabled = cdb.p("postgresql.sslmode", false)
60:      if postgres_tls_enabled
61:        postgres_tls_ca = cdb.p("postgresql.ca_cert")
62:        postgres_tls_public_cert = cdb.p("postgresql.client_cert.certificate")
63:        postgres_tls_private_key = cdb.p("postgresql.client_cert.private_key")
64:      end
65:    end
```
Tried setting postgresql.sslmode to disable and false, but that didn’t affect the error. 

Bosh env
```
Version            269.0.1 (00000000)
Director Stemcell  ubuntu-xenial/315.13
CPI                vsphere_cpi
```

Thanks in advance for any response.

**Comment by cshazi** [comment]
I got the same error message when the postgresql.sslmode parameter value was „disabled”. The value of “disabled” string as boolean value is true. The sslmode value came from the concourse_db  bosh link and you cannot replace only if you disable the consumer at bbr-atcdb job. 

My workaround is in the ops file:

```yaml
- type: replace
  path: /instance_groups/name=web/jobs/-
  value:
    name: bbr-atcdb
    properties:
      postgresql:
        host: ((postgres_host))
        port: ((postgres_port))
        database: atc
        sslmode: false
        role:
          name: ((postgres_role))
          password: ((postgres_password))
    consumes:
      concourse_db: nil
    release: concourse
```
